### ISSUE TITLE
TSX disabled by kernel (_xbegin always returns 0)

### ISSUE THREAD

**Issue by SS5hane** [schencoding/lbtree#7]
Hello,
I ran the LB+Tree code on my server  (xeon gold 5218 2.30Ghz) , but _xbegin is always 0. Then I checked the cpu info and found that TSX is currently disabled by the kernel. Could you tell me how to enable it? 

Thank you

**Comment by schencoding** [comment]
TSX is disabled by default in Linux Kernel.  It can be enabled with 'tsx=on tsx_async_abort=off mds=off' boot options.

**Comment by SS5hane** [comment]
Thanks for your answer！
